name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build1:
    name: "First build (produce config cache)"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      security-events: write
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: First build
        run: ./gradlew assembleDebug
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}

      - name: Pack configuration cache (exclude lock & gc.properties)
        run: |
          set -euo pipefail
          mkdir -p /tmp/ccache
          tar -C .gradle \
            --exclude='configuration-cache/configuration-cache.lock' \
            --exclude='configuration-cache/gc.properties' \
            -czf /tmp/ccache/config-cache.tgz \
            configuration-cache
          echo "Tar contents:"
          tar -tzf /tmp/ccache/config-cache.tgz | head -50

      - name: Upload configuration cache artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-cache-tgz
          path: /tmp/ccache/config-cache.tgz
          retention-days: 1

  build2:
    name: "Second build (consume config cache)"
    needs: build1
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      security-events: write
    timeout-minutes: 60

    steps:
      - name: Checkout (fresh)
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Download configuration cache artifact
        uses: actions/download-artifact@v4
        with:
          name: config-cache-tgz
          path: /tmp/ccache

      - name: Inspect and restore configuration cache
        run: |
          set -euo pipefail
          echo "Tar contents (before extract):"
          tar -tzf /tmp/ccache/config-cache.tgz | head -50

          mkdir -p .gradle
          tar -C .gradle -xzf /tmp/ccache/config-cache.tgz

          echo "Restored directory size:"
          du -sh .gradle/configuration-cache || true

          echo "Restored files (depth <= 3):"
          find .gradle/configuration-cache -maxdepth 3 -type f | head -100

      - name: Second build (with restored configuration cache)
        run: ./gradlew assembleDebug
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}
